name: 'AAA'

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: date
