name: 'TEST'

on: 
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'

jobs:
    job:
        name: Debug
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: echo "test"
